apiVersion: v1
kind: Pod
metadata: 
  name: voting-app
  labels:
    app: voting-app
spec:
  containers:
    - name: voting-app-cntr
      image: kodekloud/examplevotingapp_vote:v1
      ports:
        - containerPort: 80