apiVersion: apps/v1
kind: Deployment
metadata: 
  name: voting-deployment
spec:
  replicas: 3 
  selector:
    matchLabels:
      app: voting-app
  template:
    metadata: 
      name: voting-app
      labels:
        app: voting-app
    spec:
      containers:
        - name: voting-app-cntr
          image: kodekloud/examplevotingapp_vote:v1
          ports:
            - containerPort: 80
    