apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-service
spec:
  type: NodePort
  selector:
    app: elasticsearch-pod
    type: data-source
  ports:
   - port: 9200
     targetPort: 9200
     nodePort: 30008
