apiVersion: v1
kind: Pod
metadata:
  name: elasticsearch-pod
  labels:
    app: elasticsearch-pod
    type: data-source
spec:
  containers:
    - name: elasticsearch-container
      image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
      ports:
        - containerPort: 9200
